voiceflow/alexa-runtime

lib/services/voiceflow/handlers/display/index.ts, lib/services/voiceflow/handlers/display/responseBuilder.ts, lib/services/voiceflow/handlers/displayV2/index.ts, tests/lib/services/voiceflow/handlers/display/index.unit.ts
**Fixes or implements [CORE-1816](https://voiceflow.atlassian.net/browse/CORE-1816)**
=> fix: apl cmd variables (CORE-1816)

lib/services/voiceflow/handlers/noMatch.ts, tests/lib/services/voiceflow/handlers/noMatch.unit.ts
creator app portion: https://github.com/voiceflow/creator-app/pull/2366
=> fix: remove empty reprompt speaks (CORE-4085)

lib/services/alexa/customDynamoAdapter.ts, lib/services/alexa/index.ts, tests/lib/services/alexa/customDynamoAdapter.unit.ts, tests/lib/services/alexa/index.unit.ts
Fixes https://voiceflow.atlassian.net/browse/CORE-4718
=> fix: set convertEmptyValues to false for the DynamoDB instance (CORE-4718)

config.ts, lib/clients/metrics.ts, package.json, tests/lib/clients/metrics.unit.ts, types.ts, yarn.lock
requires `CONFIG_ID_HASH` env var in alexa-runtime prod
=> feat: unhashed metrics

README.md
Add code analysis badges to the `README`
=> docs(readme): add codecov and cirecleci badges (CORE-000)

config.ts, lib/services/runtime/handlers/card.ts, lib/services/runtime/handlers/directive.ts, lib/services/runtime/handlers/display/index.ts, lib/services/runtime/handlers/display/responseBuilder.ts, lib/services/runtime/handlers/displayV2/index.ts, lib/services/runtime/handlers/interaction.ts, lib/services/runtime/handlers/noMatch.ts, lib/services/runtime/handlers/reminder.ts, lib/services/runtime/handlers/speak.ts, lib/services/runtime/handlers/state/stream.ts, lib/services/runtime/handlers/stream.ts, lib/services/runtime/utils.ts, package.json, typings/voiceflow__common.d.ts, yarn.lock
**Fixes or implements CORE-XXX**
=> feat: common to ts (CORE-4920) 

.circleci/config.yml, .depcheckrc, .huskyrc.json, .lintstagedrc.js, package.json, typings/talisman.d.ts, yarn.lock
Update `fixpack`, `husky` and `lint-staged`, remove unused dependencies, add `depcheck` to ci
=> chore(deps): remove unused dependencies

lib/services/alexa/request/lifecycle/initialize.ts, package.json, yarn.lock
**Fixes or implements CORE-5385**
Upgrading the dependencies
`yarn upgrade @voiceflow/api-sdk@1.28.0 @voiceflow/general-types@1.36.0 @voiceflow/runtime@1.25.0 @voiceflow/alexa-types@1.44.0`
None
| `alexa-runtime` | [link](https://github.com/voiceflow/alexa-runtime/pull/141) |
| `google-runtime`     | [link](https://github.com/voiceflow/google-runtime/pull/87) |
| `general-runtime`     | [link](https://github.com/voiceflow/general-runtime/pull/84) |
| `general-service`     | [link](https://github.com/voiceflow/general-service/pull/72) |
| `luis-authoring-service` | [link](https://github.com/voiceflow/luis-authoring-service/pull/48) |
| `database-cli` | [link](https://github.com/voiceflow/database-cli/pull/55) |
- …
=> feat: upgrading dependencies (CORE-5385)

package.json, yarn.lock
**Fixes or implements CORE-5385**
Updating dependencies to fix desync issue.
`yarn upgrade @voiceflow/api-sdk@1.28.0 @voiceflow/general-types@1.36.0 @voiceflow/alexa-types@1.45.0 @voiceflow/runtime@1.26.0`
None
None
See ticket
=> feat: updating depends to fix deps desync issue (CORE-5385)

yarn.lock
=> chore: upgrading git-branch-check (VF-285)

package.json, yarn.lock
=> fix: bump bump bump (CORE-000)

.gitignore, package.json, sonar-project.properties
=> ci: added sonar coverage

package.json, yarn.lock
**Fixes or implements VF-185**
* update `@voiceflow/*` dependencies to include new expression types
=> feat: update @voiceflow/* dependencies (VF-185)

.circleci/config.yml
=> feat: add warden to prod (VF-1007)

config.ts, lib/clients/analytics.ts, lib/clients/index.ts, lib/clients/ingest-client.ts, lib/services/alexa/request/audioPlayerEvent.ts, lib/services/alexa/request/intent/index.ts, lib/services/alexa/request/launch.ts, lib/services/alexa/request/lifecycle/initialize.ts, lib/services/alexa/request/lifecycle/response.ts, lib/services/alexa/request/lifecycle/update.ts, package.json, tests/lib/clients/analytics.unit.ts, tests/lib/clients/ingest-client.unit.ts, tests/lib/services/alexa/request/intent/index.unit.ts, tests/lib/services/alexa/request/launch.unit.ts, tests/lib/services/alexa/request/lifecycle/initialize.unit.ts, tests/lib/services/alexa/request/lifecycle/response.unit.ts, tests/lib/services/alexa/request/lifecycle/update.unit.ts, types.ts, typings/ruddersack.d.ts, yarn.lock
**Fixes or implements VF-1239**
Added analytics system to this runtime
The development changes a little bit from general runtime, it calls one per response and one per request.
=> feat: add analytics client to alexa runtime (VF-1239)

lib/clients/analytics.ts, lib/clients/ingest-client.ts, lib/constants/flags.ts, lib/services/alexa/request/lifecycle/response.ts, lib/services/alexa/request/lifecycle/update.ts, package.json, tests/lib/clients/analytics.unit.ts, tests/lib/services/alexa/request/lifecycle/response.unit.ts, tests/lib/services/alexa/request/lifecycle/update.unit.ts
=> feat: new TS db schema (VF-1305)

lib/services/alexa/request/lifecycle/initialize.ts, lib/services/alexa/request/lifecycle/response.ts, lib/services/alexa/request/lifecycle/update.ts
=> fix: added try catch to the analytics system (VF-1410)

.circleci/config.yml
=> ci: added e2e checks

config.ts, lib/clients/analytics.ts
=> fix: fix alexa runtime when is called using the aduiplayer interface (VF-1440)

.circleci/config.yml
=> ci: added cache version

backend/constants.ts, backend/expressMiddleware.ts, config.ts, types.ts
**Fixes or implements VF-1399**
Loosen request timeout to allow more complex API blocks.
- voiceflow/general-runtime#161
- voiceflow/google-runtime#126
=> feat: better support for big JSON (VF-1399)

lib/clients/analytics.ts
=> chore: disable ingest 

backend/expressMiddleware.ts, lib/clients/analytics.ts, lib/middlewares/alexa.ts, lib/services/adapter/index.ts, lib/services/alexa/request/error.ts, lib/services/alexa/request/lifecycle/initialize.ts, lib/services/alexa/request/lifecycle/response.ts, lib/services/alexa/request/lifecycle/runtime.ts, lib/services/alexa/request/sessionEnded.ts, package.json, server.ts, start.ts, tests/lib/services/alexa/request/sessionEnded.unit.ts, yarn.lock
**Fixes or implements VF-1476**
Cleanup logging.
- https://github.com/voiceflow/general-runtime/pull/165
- https://github.com/voiceflow/alexa-runtime/pull/190
- https://github.com/voiceflow/google-runtime/pull/131
- voiceflow/logger#26
=> fix: cleanup logs (VF-1476)

lib/services/alexa/request/error.ts
Fix a small formatting error in one of the error logging messages.
- Bug introduced in #190
=> fix: fix typo in error logging message (VF-000)

.github/workflows/delete-env.yaml, .github/workflows/preview-env.yaml
`thollander/actions-comment-pull-request` changed default branch from master to main
=> chore: fixes github action incorrect branch name target (VF-000)

lib/services/alexa/request/event/index.ts, tests/lib/clients/analytics.unit.ts, tests/lib/services/alexa/request/event/index.unit.ts, tests/lib/services/alexa/request/event/runtime.unit.ts, tests/lib/services/voiceflow/handlers/displayV2.unit.ts, tests/lib/services/voiceflow/handlers/displayV2/rename.unit.ts
**Fixes or implements VF-1872**
Add tests
=> fix: add tests (VF-1872)

lib/clients/analytics.ts
**Fixes or implements VF-1881**
re-enable the analytics from when they were disabled in #189 
- voiceflow/google-runtime#142
=> feat: re-enable analytics (VF-1881)

.github/workflows/rebase.yaml, .github/workflows/rebase_all.yaml
**Part or VF-2041**
This fixes the comment spam on most PRs caused by the repeatedely faiing to rebase on the recently added rebasing workflows.
=> ci: bump rebase action version (VF-2041)

.circleci/config.yml
This fixes the e2e failures by updating to the latest version of voiceflow/commmon orb.
=> fix(deps): bump orb version (VF-000)

lib/services/alexa/request/lifecycle/initialize.ts, lib/services/alexa/request/lifecycle/response.ts, tests/lib/services/alexa/request/lifecycle/response.unit.ts
=> fix: goto delegation (VF-000)

lib/services/alexa/request/lifecycle/response.ts, package.json, tests/lib/services/alexa/request/lifecycle/response.unit.ts, yarn.lock
**Fixes or implements VF-2366**
So this PR https://github.com/voiceflow/alexa-runtime/commit/5b2f90f94d73bdb42668642ba4a2a3188c14852e#diff-6b10399bd39c679ea6989d3aec659abe31bdc6cecac7364f0eb284c2b8111254L26-L34
shuffled around the order of things.
This is infuriating but apparently, there's a side effect on the `reprompt` call that sets `shouldEndSession` back to false? That's crazy.
=> fix: skills not ending (VF-2366)

lib/services/runtime/handlers/noMatch.ts
=> fix: no-match cleanup (VF-000)

lib/controllers/alexa.ts
log every skill that comes in.
Revert this once we have the parameters we need
=> fix: debug log (VF-000)

config.ts, lib/services/runtime/handlers/index.ts, types.ts
based on the general runtime changes pipe through params so that their API can handle larger loads.
Done through this: https://github.com/voiceflow/general-runtime/commit/a5e59ce4d0c14027c69eafd3cbb084f573df2f69
=> fix: pipe api config (VF-000)

lib/clients/mongodb.ts, lib/clients/postgres.ts
**Fixes or implements VF-2863**
Do not use the assertion operator, as the client may be undefined.
=> fix: dont assert db client (VF-2863)

.circleci/continue_config.yml.tmpl, .circleci/values.test.json
* linear [ticket](https://linear.app/voiceflow/issue/IN-1212/add-e2e-log-collection-to-all-repositories) 
* add e2e logging capability
=> feat: add e2e logging to all repos (IN-1212)

.circleci/continue_config.yml.tmpl
* Linear [ticket](https://linear.app/voiceflow/issue/IN-1271/add-events-to-e2e-logs) 
* Include kubernetes events in the e2e gathered logs 
* https://github.com/voiceflow/orb-common/pull/264
* https://github.com/voiceflow/infrastructure/pull/704
=> feat: add kubernetes events to logs(IN-1271)
