lib/services/alexa/request/lifecycle/context.ts

Fixes - [JIRA](https://voiceflow.atlassian.net/browse/CORE-4219)
Issue:
When a skill is invoked with one shot intent instead of regular invocation, and also if the skill has been invoked previously, and set the value of slot in previous session, the new one shot invocation would use the value of slot from previous session rather than from new session. 
In nutshell, `buildContext` Alexa lifecycle was not considering the session when fetching attributes.

fix: one shot slot bug (CORE-4219)

---

lib/services/voiceflow/handlers/interaction.ts

this is a bit weird, but if a choice has no port, it technically leads out to `null` and should be considered handled.
The problem is that if you go down a `null` port it keeps trying to handle it through the `commandHandler` and `noMatchHandler` which leads to weird behavior.
now `null` or `undefined` is a big difference in falsy values for `nextId`
the other way to do this is default `nextId = null` and have a `handled: boolean` flag

fix: null choices not handled

---

lib/clients/index.ts
lib/clients/prototypeServerDataApi.ts
lib/services/test/index.ts
lib/services/voiceflow/handlers/command.ts
lib/services/voiceflow/handlers/interaction.ts
lib/services/voiceflow/utils.ts
package.json
tests/lib/clients/index.unit.ts
tests/lib/services/test/index.unit.ts
tests/smokeTest/smokeTestRunner.ts
yarn.lock

- https://github.com/voiceflow/creator-api/pull/560 - added prototype-programs endpoints, added support for prototype  field in version, replaced TEST_ENDPOINT with PROTOTYPE_ENDPOINT
- https://github.com/voiceflow/server-data-api/pull/37 - removed getTestDiagram and introduced prototype-programs/:programID endpoint
- https://github.com/voiceflow/platform/pull/33 - added PrototypeCloneHandlers, added PrototypeCompiler and compilerType (COMPILE|PROTOTYPE|SURVEY), add inMemoryMode to clone diagram to do not store diagrams
- https://github.com/voiceflow/general-service/pull/9 - introduced compiler endpoint to compile diagrams out of the jobs (will be used in platform services)
- https://github.com/voiceflow/runtime/pull/69 - removed getTestProgram method, updated libs, added platform arg to …

fix: remove prototype related code

---

lib/services/alexa/request/error.ts
lib/services/alexa/request/playback/index.ts

so it turns out the issue was that the request object was not extensible
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/preventExtensions
we were faking these touch commands as intents for the runtime to process.
Also whenever you handle a `PlaybackController` event, you can't return a speak or reprompt - so just covering that base as well.
Also our error logging SUCKS - updated it to actually show the errors.

fix: display stream pause

---

lib/services/adapter/index.ts
tests/lib/services/adapter/index.unit.ts

saw this error on datadog 
`context adapter err: Cannot read property '0' of undefined`.
Only place where we are using `0` is when accessing the first el of the globals array [here](https://github.com/voiceflow/alexa-client/blob/cec33e0de7ececdf01415b33960993db8bd19275/lib/services/adapter/utils.ts#L122). Looked at the user's session and globals is definitely there. Only way I see this happening is if for some reason the `getPersistentAttributes` returns `{ attributes: state, id: string}` instead of just `state`. Put in a defensive clause for this case.

fix: extract attributes (CORE-5076)

---

lib/controllers/alexa.ts
lib/services/alexa/request/intent/index.ts
lib/services/runtime/handlers/userInfo/utils.ts
tests/lib/services/voiceflow/handlers/userInfo/utils.unit.ts

**Fixes or implements CORE-000**
so amazon decided to apparently invalid their whole permissions event change system, so now our `runtime.storage.get<string[]>(S.PERMISSIONS)` is worthless to check against. The best way to check for permissions is now to actually make a general API call (like .getReminders) and see if it fails or passes

fix: reminder permissions (CORE-000)

---

lib/constants/flags.ts
lib/services/alexa/request/lifecycle/initialize.ts
lib/services/alexa/request/lifecycle/response.ts
lib/services/alexa/request/lifecycle/runtime.ts
tests/lib/services/alexa/request/lifecycle/initialize.unit.ts
tests/lib/services/alexa/request/lifecycle/response.unit.ts
tests/lib/services/alexa/request/lifecycle/runtime.unit.ts

this is an emergency fix for Nicolas who is working with a client. Basically Alexa is really really particular about this field "shouldEndSession" in the response, as an escape hatch, through the code block, we will allow the user to override the response object that we normally generate.
I removed the code block endpoint entirely (since the new conditions block is coming in local anyways) mostly because we need to do `shouldEndSession: undefined` and when you send `undefined` over HTTP JSON the variable is just completely unset.

feat: response variable (VF-000)

---

backend/api/routers/alexa.ts
package.json
yarn.lock

**Fixes or implements VF-991**
Replace `body-parser` with [voiceflow/body-parser](https://github.com/voiceflow/body-parser) and use `secure-json-parse` to avoid prototype poisoning vulnerabilities
| voiceflow/alexa-service#149     | [link](https://github.com/voiceflow/google-service/pull/149) |
| voiceflow/creator-api#692     | [link](https://github.com/voiceflow/creator-api/pull/692) |
| voiceflow/general-service#110     | [link](https://github.com/voiceflow/general-service/pull/110) |
| voiceflow/google-service#99     | [link](https://github.com/voiceflow/google-service/pull/99) |
| voiceflow/canvas-export#45     | [link](https://github.com/voiceflow/canvas-export/pull/45) |
| voiceflow/backend-template#14     | …

feat: use `secure-json-parse` and `@voiceflow/body-parser` (VF-991)

---

lib/constants/flags.ts
lib/services/alexa/request/audioPlayerEvent.ts
lib/services/alexa/request/intent/index.ts
lib/services/alexa/request/launch.ts
lib/services/alexa/request/lifecycle/response.ts
lib/services/alexa/request/lifecycle/update.ts
tests/lib/services/alexa/request/intent/index.unit.ts
tests/lib/services/alexa/request/launch.unit.ts
tests/lib/services/alexa/request/lifecycle/response.unit.ts
tests/lib/services/alexa/request/lifecycle/update.unit.ts

There shouldn't be a reason why we need to separate the `Event.TURN` from the `Event.INTERACT` - they are both generated after the actual runtime has executed and generated a new state. 
Previously the `Event.TURN` call in update was actually blocking until the request resolves (`await`)
Now both analytics tracking calls are async (not in the same eventloop thread).
Also we were doing this in the response before:
```
try {
....
runtime.services.analyticsClient.track ...
} catch (error) {
....
}
```
The was no `await` on the promise above so it wouldn't be catching anyways.
Also its nicer to just put them in one place. We could probably do both as a singular API call if we change the ingest service.
| ------------------- …

fix: clean ingest service (VF-000)

---

config.ts

**Fixes or implements VF-1549**
Reduce the default timeout from 30s to 10s.
- voiceflow/alexa-runtime#186
- voiceflow/google-runtime#127
- voiceflow/general-runtime#164

fix: set default timeout time to 10s (VF-1549)

---

config.ts
lib/services/alexa/request/sessionEnded.ts
types.ts

**Fixes or implements VF-1479**
Adds a `PRIVATE_LOGS` boolean environment variable whether to censor certain sensitive fields in logs (ex. API keys)
Only one instance of a sensitive key was reported, so that specific spot was updated to censor it.
Set the `PRIVATE_LOGS` environment variable to the string `true` to enable this option.
The option is casted from a string to a boolean, so any string, even `false` will enable it.
Only a [falsy string](https://developer.mozilla.org/en-US/docs/Glossary/Falsy#:~:text=%22%22%2C%20%27%27%2C%20%60%60-,Empty%20string%20value.,-null) will disable it, in JS this means an empty string.
The default value is to leave it disabled.

feat: add `PRIVATE_LOGS` boolean env var (VF-1479)

---

lib/services/runtime/handlers/userInfo/utils.ts
tests/lib/clients/analytics.unit.ts
tests/lib/services/voiceflow/handlers/userInfo/utils.unit.ts

**Fixes or implements VF-1845**
Add the Amazon Pay option in the User Info Step.
This will add payments:autopay_consent permission to the skill manifest to avoid users manually update it every time they upload a skill.
As permission is not needed here and we don't want to generate a card for it on user's end, we will ignore the card generation and only check the permission status = 'GRANTED' 
You want to use the Nico/amazon-pay/VF-1845 branch for creator-app as well as alexa-runtime
| creator-app | [https://github.com/voiceflow/creator-app/tree/Nico/amazon-pay/VF-1845](https://github.com/voiceflow/creator-app/tree/Nico/amazon-pay/VF-1845) |

feat: add amazon pay to user info step (VF-1845)

---

.circleci/config.yml

**Fixes or implements VF-2100**
Now that this service has been removed from e2e, we do not need to run e2e.

ci: remove unnecessary e2e test (VF-2100)

---

.circleci/config.yml
Dockerfile
Dockerfile.e2e

**Fixes or implements VF-2065**
upgrade to node16 during the build process and on runtime
upgrading the executors to node 16 on our orb
deep Test this before merge

feat: upgrade to Node.js v16 (VF-2065)

---

lib/constants/flags.ts
lib/services/alexa/request/lifecycle/response.ts
lib/services/runtime/handlers/interaction.ts
tests/lib/services/alexa/request/lifecycle/response.unit.ts
tests/lib/services/voiceflow/handlers/interaction.unit.ts

**Fixes or implements VF-2137**
did some more experimentation with the intent delegation:
https://developer.amazon.com/en-US/blogs/alexa/alexa-skills-kit/2019/03/intent-chaining-for-alexa-skill
Checked that it worked for intents with no slots i.e. (AMAZON.HelpIntent) as well as intents with slots defined.
I know @leartgjoni-voiceflow tried last time, but I think what was really bait was the `slots: {}` parameter in the delegate directive. If you leave it undefined, which the type allows, it will crash.
Here's my unscientific expirement:

feat: use delegation goto (VF-2137)

---

.circleci/config.yml
Dockerfile
Dockerfile.e2e
lib/services/alexa/request/event/index.ts
lib/services/alexa/request/sessionEnded.ts
package.json
tests/lib/services/alexa/request/event/index.unit.ts
yarn.lock

All that changed is this:
```
if (runtime.stack.getSize() === 0) {
await utils.initialize(runtime, input);
await runtime.hydrateStack();
}
const canHandle = !!utils.getEvent(runtime);
if (canHandle) input.attributesManager.setPersistentAttributes(runtime.getRawState());
return canHandle;
```
What's happening is if an Alexa event comes in and the Voiceflow stack is empty, now we insert the root/base flows along with all their commands so these commands will catch:

fix: alexa events (VF-000)

---

lib/services/alexa/constants.ts
lib/services/alexa/request/lifecycle/response.ts
lib/services/alexa/types.ts
tests/lib/services/alexa/request/lifecycle/response.unit.ts

**Fixes or implements VF-2475**
Basically Nico sums it up here nicely:
You can not send an output or reprompt when these requests are given. Even if the user doesn't have a speak block we were still throwing these in.
Amazon docs:
https://developer.amazon.com/en-US/docs/alexa/custom-skills/audioplayer-interface-reference.html#valid-response-types-2
https://developer.amazon.com/en-US/docs/alexa/custom-skills/audioplayer-interface-reference.html#valid-response-types-2

fix: disable output with audioplayer events (VF-2475)

---

lib/clients/analytics.ts

we get tens of thousands every day on our alexa runtime service.
This is because we've already removed the `/convert/` endpoint entirely from `server-data-api`
while this error only affects our analytics/logs and not the actual runtime response, its not as bad
But it does make our logs useless and cost a lot of money.

fix: stop propagation of errors [bugfix] (CT-000)

---

.circleci/continue_config.yml.tmpl

Use latest sonarcloud orb vesrsion

ci(sonar): use latest sonarcloud orb (IN-976)

---

.circleci/continue_config.yml.tmpl

**Fixes or implements DX-1583**
Remove the override to use `ci` branch for smoke tests, it will now track `master`
- New required environment variables
- Renaming of interfaces (API routes, request/response interface, etc)
- Bug fixes are accompanied by an updated or new test
- New features are accompanied by a new test

ci: use master branch for smoke tests (DX-1583)

---

.circleci/continue_config.yml.tmpl

**Fixes or implements IN-947**
Integrate e2e pooling for smoke tests
- https://github.com/voiceflow/XXXXXXXXX/pull/123
- New required environment variables
- Renaming of interfaces (API routes, request/response interface, etc)
- Bug fixes are accompanied by an updated or new test
- New features are accompanied by a new test

feat: integrate e2e env pooling for smoke test (IN-947)
